version: "3.8"
 
services:
 
  #################################
  # Book: The Book microservice
  #################################
  book:
    image: verwinkwa/book:1.0
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/book
 
  ###############################################
  # callbook: The test_invoke_http.py program
  ###############################################
  callbook:
    image: verwinkwa/callbook:1.0
    depends_on:
      - book
    environment:
      bookURL: http://book:5000/book