version: "3.8"

volumes:
  rabbitmq_data:

services:
 
  ###################################
  # Booking: The Booking microservice
  ###################################
  booking:
    build:
      context: ./services/booking
      dockerfile: Dockerfile
    image: weixiangtoh/booking:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://admin:esdg1t32021@esd-prod.ckcprxmpwut9.us-east-1.rds.amazonaws.com:3306/booking
      PYTHONUNBUFFERED: 1
    ports:
      - "5000:5000"

  ###################################
  # Cart: The Cart microservice
  ###################################
  cart:
    build:
      context: ./services/cart
      dockerfile: Dockerfile
    image: weixiangtoh/cart:esd
    restart: always
    environment:
      cart_dbURL: mysql+mysqlconnector://admin:esdg1t32021@esd-prod.ckcprxmpwut9.us-east-1.rds.amazonaws.com:3306/cart
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
  
  ##############################################
  # Facility: The Facility microservice
  ##############################################
  facility:
    build:
      context: ./services/facility
      dockerfile: Dockerfile
    image: weixiangtoh/facility:esd
    restart: always
    environment:
      facility_dbURL: mysql+mysqlconnector://admin:esdg1t32021@esd-prod.ckcprxmpwut9.us-east-1.rds.amazonaws.com:3306/facility
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ##############################################
  # Room_Service: The Room_Service microservice
  ##############################################
  room_service:
    build:
      context: ./services/room_service
      dockerfile: Dockerfile
    image: weixiangtoh/room_service:esd
    restart: always
    environment:
      room_service_dbURL: mysql+mysqlconnector://admin:esdg1t32021@esd-prod.ckcprxmpwut9.us-east-1.rds.amazonaws.com:3306/room_service
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ############################################################
  # Nearest_Attractions: The Nearest_Attractions microservice
  ############################################################
  nearest_attractions:
    build:
      context: ./services/nearest_attractions
      dockerfile: Dockerfile
    image: weixiangtoh/nearest_attractions:esd
    restart: always
    environment:
      GOOGLE_API_KEY: "AIzaSyAw3Q7eJyqIazB2ucevU3NhnVmsqs5Z3bQ"
      PYTHONUNBUFFERED: 1
    ports:
      - "5015:5015"

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Notification: The Notification microservice
  #################################################
  notification:
    build:
      context: ./services/notification
      dockerfile: Dockerfile
    image: weixiangtoh/notification:esd
    restart: always
    depends_on:
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      SENDGRID_API_KEY: "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"
      PYTHONUNBUFFERED: 1
    ports:
      - "5004:5004"

  ##########################################################
  # Error_Service: The Long_Error_Service microservice
  ##########################################################
  error_service:
    build:
      context: ./services/error_service
      dockerfile: Dockerfile
    image: weixiangtoh/error_service:esd
    restart: always
    depends_on:
      - rabbitmq
      - cart
      - notification
      - booking
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      cart_URL: "http://cart:5001/cart"
      booking_URL: "http://booking:5000/booking"
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ##########################################################
  # Check_Cart: The Check_Cart microservice
  ##########################################################
  check_cart:
    build:
      context: ./services/check_cart
      dockerfile: Dockerfile
    image: weixiangtoh/check_cart:esd
    restart: always
    depends_on:
      - room_service
      - cart
      - facility
    environment:
      room_service_URL: "http://room_service:5003/room_service"
      cart_URL: "http://cart:5001/cart"
      facility_URL: "http://facility:5002/facility"
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ##########################################################
  # Order_Room_Service: The Order_Room_Service microservice
  ##########################################################
  order_room_service:
    build:
      context: ./services/order_room_service
      dockerfile: Dockerfile
    image: weixiangtoh/order_room_service:esd
    restart: always
    depends_on:
      - booking
      - cart
      - room_service
      - notification
      - error_service
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: "http://booking:5000/booking"
      cart_URL: "http://cart:5001/cart"
      room_service_URL: "http://room_service:5003/room_service"
      PYTHONUNBUFFERED: 1
    ports:
      - "5200:5200"

  ##########################################################
  # Book_Facilities: The Book_Facilities microservice
  ##########################################################
  book_facilities:
    build:
      context: ./services/book_facilities
      dockerfile: Dockerfile
    image: weixiangtoh/book_facilities:esd
    restart: always
    depends_on:
      - booking
      - cart
      - facility
      - notification
      - rabbitmq
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      booking_URL: "http://booking:5000/booking"
      cart_URL: "http://cart:5001/cart"
      facility_URL: "http://facility:5002/facility"
      PYTHONUNBUFFERED: 1
    ports:
      - "5300:5300"

  ##########################################################
  # Payment: The Payment microservice
  ##########################################################
  payment:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    image: weixiangtoh/payment:esd
    restart: always
    environment:
      STRIPE_SK_API_KEY: "sk_test_51HeLb7GWjRGxBOOYruap689xNCFhMWetmp25MiJz4LGZoJPqSLTCsNhhoqtvt6DW6qKRHf7iiyyZMeRbN61lL6A500O0PzD1vM"
      PYTHONUNBUFFERED: 1
    ports:
      - "4242:4242"

  ##########################################################
  # process_checkout: The process_checkout microservice
  ##########################################################
  process_checkout:
    build:
      context: ./services/process_checkout
      dockerfile: Dockerfile
    image: weixiangtoh/process_checkout:esd
    restart: always
    depends_on:
      - booking
      - cart
      - payment
      - notification
    environment:
      booking_URL: "http://booking:5000/booking"
      cart_URL: "http://cart:5001/cart"
      payment_URL: "http://payment:4242/create-checkout-session"
      PYTHONUNBUFFERED: 1
    ports:
      - "5400:5400"
